
services:
  server:
    build:
      context: .
      target: production
    ports:
      - 3000:3000
    container_name: server-container
    # env_file:
    #  - .env.local
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"
